name: Build

on: pull_request

jobs:
  build:
    runs-on: macos-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Install xcodegen
        run: brew install xcodegen
      -
        name: Generate Project
        run: xcodegen
      -
        name: Build App
        run: xcodebuild
